spring:
  application:
    name: code-test

# --- kafka -------
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: health-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

  datasource:
    url: jdbc:mysql://localhost:3306/dev_db?serverTimezone=UTC&sessionVariables=time_zone='%2B00:00'&useSSL=false
    username: ${DB_USERNAME:dev}
    password: ${DB_PASSWORD:dev}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 20000
      idle-timeout: 300000

  # --- Redis ---
  data:
    redis:
      host: localhost
      port: 6379

  # --- JPA / Hibernate ---
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        jdbc:
          time_zone: UTC
          force_utc_timezone: true
        type:
          descriptor:
            sql:
              jdbc_timezone_fallback: true

  sql:
    init:
      mode: never

# --- JWT Settings ---
jwt:
  secret: U3HeWuk51RdLakyXCFepv7lqKxy+4PCHCF3zEsri721rrwZlbIxW2gChrvaXSORVO+j1RkpELqwpwlJf5DSEZQ==
  token:
    access:
      expired:
        time: 3000000
    refresh:
      expired:
        time: 30000000

logging:
  level:
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
